class Locators:
    home_login_button = '//a[@class="login-myact"]'
    sign_up_link = '//a[text()=" Sign Up"]'
    first_name_field = '//input[@id="reg_sr_firstname"]'
    last_name_field = '//input[@id="reg_sr_lastname"]'
    email_address_field = '//input[@id="reg_email"]'
    signup_password = '//input[@id="reg_password"]'
    select_country = '//select[@id="ip-vk-country-obts"]'
    phone_num_field = '//input[@id="reg_sr_phone"]'
    register_button = '//input[@type="submit"]'
    error_text_msg = '//span[@class="lwa-status lwa-status-invalid"]'
    logged_in_user_btn = '//a[@class="loggedinuser-btn"]'
    log_out_btn = '//a[@id="destroy-sessions"]'
    user_name_field = '//input[@name="log"]'
    login_password_field = '//input[@name="pwd"]'
    Log_In = '//input[@id="wp-submit"]'
    submt_Log_In_Btn = '//input[@id="lwa_wp-submit"]'
    my_course_btn = '//*[@id="menu-course-new-top-menu"]/span[3]/a'
